<?xml version="1.0" encoding="utf-8"?><Database Name="groupDB" Class="GroupDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\groupDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="groupDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="PROD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROD_NAME" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PROD_PRICE" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PROD_CATEGORY" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="PROD_DESCRIPTION" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PROD_QUANTITY_AVAILABLE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PROD_IMAGE_PATH" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PROD_ISBN" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PROD_AUTHOR" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="PRODUCT_SHOPPING_CART_ITEM" Member="SHOPPING_CART_ITEMs" ThisKey="PROD_ID" OtherKey="ProductID" Type="SHOPPING_CART_ITEM" />
      <Association Name="PRODUCT_INVOICE_PRODUCT" Member="INVOICE_PRODUCTs" ThisKey="PROD_ID" OtherKey="PROD_ID" Type="INVOICE_PRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.SHOPPING_CART_ITEMS" Member="SHOPPING_CART_ITEMs">
    <Type Name="SHOPPING_CART_ITEM">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PRODUCT_SHOPPING_CART_ITEM" Member="PRODUCT" ThisKey="ProductID" OtherKey="PROD_ID" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[USER]" Member="USERs">
    <Type Name="USER">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_SURNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_GENDER" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PHONE_NUMBER" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="USER_EMAIL_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_AUTHENTICATION_LEVEL" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="USER_USER_PASSWORD" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SECURITY_QUESTION" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ANSWER" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="REG_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="USER_INVOICE" Member="INVOICEs" ThisKey="USER_ID" OtherKey="USER_ID" Type="INVOICE" />
      <Association Name="USER_COMMENT" Member="COMMENTs" ThisKey="USER_ID" OtherKey="USER_ID" Type="COMMENT" />
    </Type>
  </Table>
  <Table Name="dbo.INVOICE" Member="INVOICEs">
    <Type Name="INVOICE">
      <Column Name="INV_NUMBER" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INV_DATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="INVOICE_INVOICE_PRODUCT" Member="INVOICE_PRODUCTs" ThisKey="INV_NUMBER" OtherKey="INV_NUMBER" Type="INVOICE_PRODUCT" />
      <Association Name="USER_INVOICE" Member="USER" ThisKey="USER_ID" OtherKey="USER_ID" Type="USER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INVOICE_PRODUCT" Member="INVOICE_PRODUCTs">
    <Type Name="INVOICE_PRODUCT">
      <Column Name="PROD_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="INV_NUMBER" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="INVOICE_INVOICE_PRODUCT" Member="INVOICE" ThisKey="INV_NUMBER" OtherKey="INV_NUMBER" Type="INVOICE" IsForeignKey="true" />
      <Association Name="PRODUCT_INVOICE_PRODUCT" Member="PRODUCT" ThisKey="PROD_ID" OtherKey="PROD_ID" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.COMMENT" Member="COMMENTs">
    <Type Name="COMMENT">
      <Column Name="CMT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COMMENT" Member="COMMENT1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SUBJECT" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="USER_COMMENT" Member="USER" ThisKey="USER_ID" OtherKey="USER_ID" Type="USER" IsForeignKey="true" />
    </Type>
  </Table>
</Database>